### ISSUE TITLE
Fatal Python error: PyThreadState_Get: no current thread

### ISSUE THREAD

**Issue by tkoolen** [rdeits/PyLCM.jl#19]
I'm getting

```
Fatal Python error: PyThreadState_Get: no current thread

signal (6): Abort trap: 6
while loading /Users/twan/code/julia/RigidBodyDynamics/v0.6/PyLCM/test/runtests.jl, in expression starting on line 12
__pthread_kill at /usr/lib/system/libsystem_kernel.dylib (unknown line)
Allocations: 5324376 (Pool: 5322843; Big: 1533); GC: 9
```

during `Pkg.test("PyLCM")` with LCMCore 0.1.0 and PyCall 1.15.0 on my mac.

```julia
julia> versioninfo()
Julia Version 0.6.2
Commit d386e40c17 (2017-12-13 18:08 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin14.5.0)
  CPU: Intel(R) Core(TM) i7-3820QM CPU @ 2.70GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, ivybridge)
```

**Comment by tkoolen** [comment]
Doesn't seem to be an issue on Linux.

**Comment by rdeits** [comment]
This is usually what happens when you try to run a library compiled for python 2 in python 3 (or the reverse). It might be related to the fact that homebrew recently changed the `python` package to python3. What is your `PyCall.python` and `PyCall.pyversion`?

**Comment by tkoolen** [comment]
```julia
julia> PyCall.python
"/Users/twan/code/julia/RigidBodyDynamics/v0.6/Conda/deps/usr/bin/python"

julia> PyCall.pyversion
v"2.7.14"
```

**Comment by rdeits** [comment]
Ah, it looks like I attempted to fix this but didn't make a new release. Can you `Pkg.checkout` and `Pkg.build` PyLCM and try again?

**Comment by tkoolen** [comment]
Yep, that fixes it. Thanks.

**Comment by rdeits** [comment]
Ok, excellent. The changes in master are kind of icky (I have to manually parse your cmake cache from the LCM build in order to see if it used the wrong python version), but they're clearly necessary in cases like this. I'll make a new release momentarily.
