### ISSUE TITLE
On installing PyLCM

### ISSUE THREAD

**Issue by dehann** [rdeits/PyLCM.jl#6]
Hi @rdeits,

Maybe this helps general info for installing. Doesn't look like you published this package on common metadata (I haven't done it myself yet), so I had to install by hand. I git cloned the PyLCM.jl repo into ~/.julia/v0.4/, and then renamed the folder from PyLCM.jl to just PyLCM. The REPL didn't like the .jl piece. As a result I also removed the ~/.julia/v0.4/PyLCM/.git folder (not sure if the renaming would become an issue later).

Thereafter in Julia I had to do Pkg.build("PyLCM") regardless of my global LCM install, and only from there did a general LCM use-case work -- provided PYTHONPATH pointed to desired lcm-gen modules.

Thanks for the effort!
Dehann

**Comment by rdeits** [comment]
Thanks! I actually just got PyLCM published into METADATA a few days ago, so it's probably not in the METADATA that ships with the Julia installers. But I _think_ you should be able to do:

```
julia> Pkg.update()
julia> Pkg.add("PyLCM")
```

to update your local copy of METADATA and get PyLCM. Does that work? 

Also, there's actually a built-in process for installing non-registered packages. You can just do:

```
julia> Pkg.clone("https://github.com/rdeits/PyLCM.jl.git")
```

which should do the renaming and build steps for you, if you come across other non-registered packages that you need.

**Comment by dehann** [comment]
Got it thanks.
